baseURL = "https://c1010.netlify.com/"
languageCode = "en-us"
title = "C101 Friday Hongtao"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"


[[menu.main]]
    name = "Assignments"
    url = "/assignments/"
    weight = 1
[[menu.main]]
    name = "Slides"
    url = "/slides/"
    weight = 2
[[menu.main]]
    name = "Class Review"
    url = "/review"
    weight = 3
[[menu.main]]
    name = "Grades Distribution"
    url = "/grades"
    weight = 4


[markup]
   defaultMarkdownHandler = "goldmark"
   [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      strikethrough = true
      table = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      
[markup.tableOfContents]
  endLevel = 2
  ordered = true
  startLevel = 1